package com.perez.javah.util;

import com.perez.javah.ClassName;
import com.perez.javah.search.SearchPath;
import org.objectweb.asm.Type;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import static com.perez.javah.util.Utils.METHOD_TYPE_PATTERN;
import static com.perez.javah.util.Utils.escape;

// Generate Go binding source code based on cgo and `//export` that complies with the corresponding FFI specifications.
// Compilation and Integration: Compile using `go build -buildmode=c-shared -o libnative.so {MangledClassName}.go` within a Go module.
// The resulting dynamic library will automatically export symbols to JNI.
public class GoGenerator extends BindingGenerator {

    public GoGenerator(File outputDir) {
        super(outputDir);
    }

    public GoGenerator(File outputDir, Iterable<SearchPath> searchPaths) {
        super(outputDir, searchPaths);
    }

    public GoGenerator(File outputDir, Iterable<SearchPath> searchPaths, PrintWriter errorHandle) {
        super(outputDir, searchPaths, errorHandle);
    }

    @Override
    public String getFileExtension() {
        return "go";
    }

    @Override
    protected void writeBindings(ClassMetaInfo meta, ClassName name, PrintWriter out) {
        out.println("/* DO NOT EDIT THIS FILE - it is machine generated */");
        out.println("package main");
        out.println();
        out.println("import \"C\"");
        out.println();

        if (!meta.constants.isEmpty()) {
            out.println("// Constants for class " + name.mangledName());
            out.println("const (");
            for (Constant constant : meta.constants) {
                String cn = name.mangledName() + "_" + constant.name();
                String goType = getGoConstType(constant.value());
                String goVal = getGoConstValue(constant.value());
                out.println("\t" + cn + " " + goType + " = " + goVal);
            }
            out.println(")");
            out.println();
        }

        for (NativeMethod method : meta.methods) {
            String ret = mapTypeToGo(method.type().getReturnType());
            List<String> args = new ArrayList<>();
            args.add("env *C.JNIEnv");
            args.add(method.isStatic() ? "clazz C.jclass" : "this C.jobject");

            String[] paramTypes = mapArgsTypeToGo(method.type());
            for (int i = 0; i < paramTypes.length; i++) {
                args.add("arg" + i + " " + paramTypes[i]);
            }

            String methodName = "Java_" + name.mangledName() + "_" +
                    (meta.isOverloadMethod(method) ? method.longMangledName() : method.mangledName());

            out.println("/*");
            out.println(" * Class:     " + name.mangledName());
            out.println(" * Method:    " + method.name());
            out.println(" * Signature: " + escape(method.type().toString()));
            out.println(" */");
            // cgo directive requires immediate attachment to function signature
            out.println("//export " + methodName);
            StringBuilder fnSig = new StringBuilder();
            fnSig.append("func ").append(methodName).append("(");
            fnSig.append(String.join(", ", args));
            fnSig.append(")");
            if (!ret.equals("void")) {
                fnSig.append(" ").append(ret);
            }
            fnSig.append(" {");
            out.println(fnSig);
            out.println("\tpanic(\"unimplemented\")");
            out.println("}");
            out.println();
        }

        out.println("func main() {}");
    }

    private String getGoConstType(Object val) {
        if (val instanceof Byte) return "int8";
        if (val instanceof Short) return "int16";
        if (val instanceof Integer) return "int32";
        if (val instanceof Long) return "int64";
        if (val instanceof Character) return "uint16";
        if (val instanceof Float) return "float32";
        if (val instanceof Double) return "float64";
        return "int32";
    }

    private String getGoConstValue(Object val) {
        if (val instanceof Character) {
            return String.valueOf((int) (Character) val);
        }
        return val.toString();
    }

    private String mapTypeToGo(Type type) {
        Objects.requireNonNull(type);
        String tpe = type.toString();
        switch (tpe) {
            case "Z": return "C.jboolean";
            case "B": return "C.jbyte";
            case "C": return "C.jchar";
            case "S": return "C.jshort";
            case "I": return "C.jint";
            case "J": return "C.jlong";
            case "F": return "C.jfloat";
            case "D": return "C.jdouble";
            case "V": return "void";
            case "Ljava/lang/Class;": return "C.jclass";
            case "Ljava/lang/String;": return "C.jstring";
            case "Ljava/lang/Throwable;": return "C.jthrowable";
            case "[Z": return "C.jbooleanArray";
            case "[B": return "C.jbyteArray";
            case "[C": return "C.jcharArray";
            case "[S": return "C.jshortArray";
            case "[I": return "C.jintArray";
            case "[J": return "C.jlongArray";
            case "[F": return "C.jfloatArray";
            case "[D": return "C.jdoubleArray";
        }
        if (tpe.startsWith("[")) {
            return "C.jobjectArray";
        }
        if (tpe.startsWith("L") && tpe.endsWith(";")) {
            ClassName n = ClassName.ofInternalName(tpe.substring(1, tpe.length() - 1));
            return isThrowable(n) ? "C.jthrowable" : "C.jobject";
        }
        throw new IllegalArgumentException("Unknown type: " + type);
    }

    private String[] mapArgsTypeToGo(Type methodType) {
        Objects.requireNonNull(methodType);
        if (!METHOD_TYPE_PATTERN.matcher(methodType.toString()).matches()) {
            throw new IllegalArgumentException(methodType + " is not a method type");
        }
        Type[] args = methodType.getArgumentTypes();
        String[] ans = new String[args.length];
        for (int i = 0; i < args.length; i++) {
            ans[i] = mapTypeToGo(args[i]);
        }
        return ans;
    }
}