package com.perez.javah.util;

import com.perez.javah.ClassName;
import com.perez.javah.search.SearchPath;
import org.objectweb.asm.Type;

import java.io.File;
import java.io.PrintWriter;
import java.util.*;

import static com.perez.javah.util.Utils.METHOD_TYPE_PATTERN;
import static com.perez.javah.util.Utils.escape;

public class JNIGenerator extends BindingGenerator {

    public JNIGenerator(File outputDir) {
        super(outputDir);
    }

    public JNIGenerator(File outputDir, Iterable<SearchPath> searchPaths) {
        super(outputDir, searchPaths);
    }

    public JNIGenerator(File outputDir, Iterable<SearchPath> searchPaths, PrintWriter errorHandle) {
        super(outputDir, searchPaths, errorHandle);
    }

    @Override
    public String getFileExtension() {
        return "h";
    }

    @Override
    protected void writeBindings(ClassMetaInfo meta, ClassName name, PrintWriter out) {
        out.println("/* DO NOT EDIT THIS FILE - it is machine generated */");
        out.println("#include <jni.h>");
        out.println("/* Header for class " + name.mangledName() + " */");
        out.println();
        out.println("#ifndef _Included_" + name.mangledName());
        out.println("#define _Included_" + name.mangledName());
        out.println("#ifdef __cplusplus");
        out.println("extern \"C\" {");
        out.println("#endif");

        for (Constant constant : meta.constants) {
            String cn = name.mangledName() + "_" + constant.name();
            out.println("#undef " + cn);
            out.println("#define " + cn + " " + constant.valueToString());
        }

        for (NativeMethod method : meta.methods) {
            String ret = mapTypeToNative(method.type().getReturnType());
            List<String> args = new ArrayList<>();
            args.add("JNIEnv *");
            args.add(method.isStatic() ? "jclass" : "jobject");
            args.addAll(Arrays.asList(mapArgsTypeToNative(method.type())));

            String methodName = "Java_" + name.mangledName() + "_" +
                    (meta.isOverloadMethod(method) ? method.longMangledName() : method.mangledName());

            out.println("/*");
            out.println(" * Class:      " + name.mangledName());
            out.println(" * Method:     " + method.name());
            out.println(" * Signature:  " + escape(method.type().toString()));
            out.println(" */");
            out.println("JNIEXPORT " + ret + " JNICALL " + methodName);
            StringBuilder argsBuilder = new StringBuilder();
            for (int i = 0; i < args.size(); i++) {
                if (i > 0) {
                    argsBuilder.append(", ");
                }
                argsBuilder.append(args.get(i));
            }
            out.println("  (" + argsBuilder + ");");
            out.println();
        }

        out.println("#ifdef __cplusplus");
        out.println("}");
        out.println("#endif");
        out.println("#endif");
    }

    private String mapTypeToNative(Type type) {
        Objects.requireNonNull(type);
        String tpe = type.toString();
        if (tpe.startsWith("(")) {
            throw new IllegalArgumentException();
        }
        switch (tpe) {
            case "Z": return "jboolean";
            case "B": return "jbyte";
            case "C": return "jchar";
            case "S": return "jshort";
            case "I": return "jint";
            case "J": return "jlong";
            case "F": return "jfloat";
            case "D": return "jdouble";
            case "V": return "void";
            case "Ljava/lang/Class;": return "jclass";
            case "Ljava/lang/String;": return "jstring";
            case "Ljava/lang/Throwable;": return "jthrowable";
            case "[Z": return "jbooleanArray";
            case "[B": return "jbyteArray";
            case "[C": return "jcharArray";
            case "[S": return "jshortArray";
            case "[I": return "jintArray";
            case "[J": return "jlongArray";
            case "[F": return "jfloatArray";
            case "[D": return "jdoubleArray";
        }
        if (tpe.startsWith("[")) {
            return "jobjectArray";
        }
        if (tpe.startsWith("L") && tpe.endsWith(";")) {
            ClassName n = ClassName.ofInternalName(tpe.substring(1, tpe.length() - 1));
            if (isThrowable(n)) {
                return "jthrowable";
            } else {
                return "jobject";
            }
        }
        throw new IllegalArgumentException("Unknown type: " + type);
    }

    private String[] mapArgsTypeToNative(Type methodType) {
        Objects.requireNonNull(methodType);
        if (!METHOD_TYPE_PATTERN.matcher(methodType.toString()).matches()) {
            throw new IllegalArgumentException(methodType + " is not a method type");
        }
        Type[] args = methodType.getArgumentTypes();
        String[] ans = new String[args.length];
        for (int i = 0; i < args.length; i++) {
            ans[i] = mapTypeToNative(args[i]);
        }
        return ans;
    }
}