package com.perez.javah.util;

import com.perez.javah.ClassName;
import com.perez.javah.search.SearchPath;
import org.objectweb.asm.Type;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import static com.perez.javah.util.Utils.METHOD_TYPE_PATTERN;
import static com.perez.javah.util.Utils.escape;

// Generate Rust bindings source code that conforms to the FFI specification of the `jni-rs` library.
// Compilation and Integration: In the Cargo.toml file of the Rust project, add jni = "0.21" (or other compatible version)
// and configure crate-type = ["cdylib"]. It will then be a valid compileable template.
public class RustGenerator extends BindingGenerator {

    public RustGenerator(File outputDir) {
        super(outputDir);
    }

    public RustGenerator(File outputDir, Iterable<SearchPath> searchPaths) {
        super(outputDir, searchPaths);
    }

    public RustGenerator(File outputDir, Iterable<SearchPath> searchPaths, PrintWriter errorHandle) {
        super(outputDir, searchPaths, errorHandle);
    }

    @Override
    public String getFileExtension() {
        return "rs";
    }

    @Override
    protected void writeBindings(ClassMetaInfo meta, ClassName name, PrintWriter out) {
        out.println("/* DO NOT EDIT THIS FILE - it is machine generated */");
        out.println();
        out.println("#![allow(non_snake_case)]");
        out.println("#![allow(unused_variables)]");
        out.println();
        out.println("use jni::JNIEnv;");
        out.println("use jni::objects::{JClass, JObject, JString};");
        out.println("use jni::sys::{");
        out.println("    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble,");
        out.println("    jobject, jclass, jstring, jthrowable,");
        out.println("    jbooleanArray, jbyteArray, jcharArray, jshortArray,");
        out.println("    jintArray, jlongArray, jfloatArray, jdoubleArray, jobjectArray");
        out.println("};");
        out.println();

        if (!meta.constants.isEmpty()) {
            out.println("/* Constants for class " + name.mangledName() + " */");
            for (Constant constant : meta.constants) {
                String cn = name.mangledName() + "_" + constant.name();
                String rustType = getRustConstType(constant.value());
                String rustVal = getRustConstValue(constant.value());
                out.println("pub const " + cn + ": " + rustType + " = " + rustVal + ";");
            }
            out.println();
        }

        for (NativeMethod method : meta.methods) {
            String ret = mapTypeToRustReturn(method.type().getReturnType());
            List<String> args = new ArrayList<>();
            args.add("mut env: JNIEnv<'_>");
            args.add(method.isStatic() ? "class: JClass<'_>" : "this: JObject<'_>");

            String[] paramTypes = mapArgsTypeToRust(method.type());
            for (int i = 0; i < paramTypes.length; i++) {
                args.add("arg" + i + ": " + paramTypes[i]);
            }

            String methodName = "Java_" + name.mangledName() + "_" +
                    (meta.isOverloadMethod(method) ? method.longMangledName() : method.mangledName());

            out.println("/*");
            out.println(" * Class:     " + name.mangledName());
            out.println(" * Method:    " + method.name());
            out.println(" * Signature: " + escape(method.type().toString()));
            out.println(" */");
            out.println("#[no_mangle]");
            out.print("pub extern \"system\" fn " + methodName + "(");
            if (args.size() <= 2) {
                out.print(String.join(", ", args));
                out.print(")");
            } else {
                out.println();
                for (String arg : args) {
                    out.println("    " + arg + ",");
                }
                out.print(")");
            }

            if (ret != null && !ret.isEmpty()) {
                out.print(" -> " + ret);
            }
            out.println(" {");
            out.println("    unimplemented!()");
            out.println("}");
            out.println();
        }
    }

    private String getRustConstType(Object val) {
        if (val instanceof Byte) return "i8";
        if (val instanceof Short) return "i16";
        if (val instanceof Integer) return "i32";
        if (val instanceof Long) return "i64";
        if (val instanceof Character) return "u16";
        if (val instanceof Float) return "f32";
        if (val instanceof Double) return "f64";
        return "i32";
    }

    private String getRustConstValue(Object val) {
        if (val instanceof Character) {
            return ((int) (Character) val) + "u16";
        }
        if (val instanceof Float) {
            return val + "f32";
        }
        if (val instanceof Double) {
            return val + "f64";
        }
        if (val instanceof Long) {
            return val + "i64";
        }
        if (val instanceof Integer) {
            return val + "i32";
        }
        if (val instanceof Short) {
            return val + "i16";
        }
        if (val instanceof Byte) {
            return val + "i8";
        }
        return val.toString();
    }

    private String mapTypeToRustParam(Type type) {
        Objects.requireNonNull(type);
        String tpe = type.toString();
        switch (tpe) {
            case "Z": return "jboolean";
            case "B": return "jbyte";
            case "C": return "jchar";
            case "S": return "jshort";
            case "I": return "jint";
            case "J": return "jlong";
            case "F": return "jfloat";
            case "D": return "jdouble";
            case "Ljava/lang/String;": return "JString<'_>";
            case "Ljava/lang/Class;": return "JClass<'_>";
            case "[Z": return "jbooleanArray";
            case "[B": return "jbyteArray";
            case "[C": return "jcharArray";
            case "[S": return "jshortArray";
            case "[I": return "jintArray";
            case "[J": return "jlongArray";
            case "[F": return "jfloatArray";
            case "[D": return "jdoubleArray";
        }
        if (tpe.startsWith("[")) {
            return "jobjectArray";
        }
        if (tpe.startsWith("L") && tpe.endsWith(";")) {
            return "JObject<'_>";
        }
        throw new IllegalArgumentException("Unknown param type: " + type);
    }

    private String mapTypeToRustReturn(Type type) {
        Objects.requireNonNull(type);
        String tpe = type.toString();
        switch (tpe) {
            case "V": return null;
            case "Z": return "jboolean";
            case "B": return "jbyte";
            case "C": return "jchar";
            case "S": return "jshort";
            case "I": return "jint";
            case "J": return "jlong";
            case "F": return "jfloat";
            case "D": return "jdouble";
            case "Ljava/lang/String;": return "jstring";
            case "Ljava/lang/Class;": return "jclass";
            case "Ljava/lang/Throwable;": return "jthrowable";
            case "[Z": return "jbooleanArray";
            case "[B": return "jbyteArray";
            case "[C": return "jcharArray";
            case "[S": return "jshortArray";
            case "[I": return "jintArray";
            case "[J": return "jlongArray";
            case "[F": return "jfloatArray";
            case "[D": return "jdoubleArray";
        }
        if (tpe.startsWith("[")) {
            return "jobjectArray";
        }
        if (tpe.startsWith("L") && tpe.endsWith(";")) {
            ClassName n = ClassName.ofInternalName(tpe.substring(1, tpe.length() - 1));
            return isThrowable(n) ? "jthrowable" : "jobject";
        }
        throw new IllegalArgumentException("Unknown return type: " + type);
    }

    private String[] mapArgsTypeToRust(Type methodType) {
        Objects.requireNonNull(methodType);
        if (!METHOD_TYPE_PATTERN.matcher(methodType.toString()).matches()) {
            throw new IllegalArgumentException(methodType + " is not a method type");
        }
        Type[] args = methodType.getArgumentTypes();
        String[] ans = new String[args.length];
        for (int i = 0; i < args.length; i++) {
            ans[i] = mapTypeToRustParam(args[i]);
        }
        return ans;
    }
}