/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_perez_netdiag_Service_LDNetTraceRoute */

#ifndef _Included_com_perez_netdiag_Service_LDNetTraceRoute
#define _Included_com_perez_netdiag_Service_LDNetTraceRoute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_perez_netdiag_Service_LDNetTraceRoute
 * Method:    startJNICTraceRoute
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_perez_netdiag_Service_LDNetTraceRoute_startJNICTraceRoute
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
